/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Demographic;
import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author shiva
 */
public class CreateDemoGraphic extends javax.swing.JPanel {

    /**
     * Creates new form CreateDemoGraphic
     */
    public Demographic demographic;
    public Person person;
    public CreateDemoGraphic(Demographic demo, Person person) {
        initComponents();
        this.demographic = demo;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createDemoGraphicInfo = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        lastName = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JLabel();
        phoneNumberText = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JLabel();
        dateOfBirthText = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        height = new javax.swing.JLabel();
        heightText = new javax.swing.JTextField();
        weight = new javax.swing.JLabel();
        weightText = new javax.swing.JTextField();
        ssn = new javax.swing.JLabel();
        ssnText = new javax.swing.JTextField();
        saveDemo = new javax.swing.JButton();

        setBackground(new java.awt.Color(169, 228, 220));

        createDemoGraphicInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createDemoGraphicInfo.setForeground(new java.awt.Color(255, 0, 0));
        createDemoGraphicInfo.setText("PLEASE ENTER THE DEMOGRAPHIC INFORMATION BELOW");

        firstName.setBackground(new java.awt.Color(0, 255, 0));
        firstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        firstName.setText("First Name:");

        firstNameText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        lastName.setBackground(new java.awt.Color(0, 255, 0));
        lastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lastName.setText("Last Name:");

        lastNameText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        phoneNumber.setBackground(new java.awt.Color(0, 255, 0));
        phoneNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phoneNumber.setText("Phone Number:");

        phoneNumberText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        dateOfBirth.setBackground(new java.awt.Color(0, 255, 0));
        dateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateOfBirth.setText("Date Of Birth:");

        dateOfBirthText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        age.setBackground(new java.awt.Color(0, 255, 0));
        age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        age.setText("Age:");

        ageText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        height.setBackground(new java.awt.Color(0, 255, 0));
        height.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        height.setText("Height:");

        heightText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        weight.setBackground(new java.awt.Color(0, 255, 0));
        weight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        weight.setText("Weight:");

        weightText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ssn.setBackground(new java.awt.Color(0, 255, 0));
        ssn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ssn.setText("SSN:");

        ssnText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        saveDemo.setBackground(new java.awt.Color(204, 0, 204));
        saveDemo.setText("Save");
        saveDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDemoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(createDemoGraphicInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(lastNameText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(phoneNumberText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(dateOfBirthText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(ageText))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(heightText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(weightText))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(ssnText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(saveDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(createDemoGraphicInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOfBirthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ssnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(saveDemo)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void saveDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDemoActionPerformed
        // TODO add your handling code here:
        this.demographic.setFirstName(firstNameText.getText());
        this.demographic.setLastName(lastNameText.getText());
        this.demographic.setPhoneNumber(phoneNumberText.getText());
        this.demographic.setDateOfBirth(dateOfBirthText.getText());
        this.demographic.setAge(Integer.parseInt(ageText.getText()));
        this.demographic.setHeight(Integer.parseInt(heightText.getText()));
        this.demographic.setWeight(Integer.parseInt(weightText.getText()));
        this.demographic.setSocialSecurityNumber(ssnText.getText());
        
        this.person.setDemographicInfo(this.demographic);
        
        JOptionPane.showMessageDialog(this, "The Demographic Info has been submitted");

    }//GEN-LAST:event_saveDemoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JTextField ageText;
    private javax.swing.JLabel createDemoGraphicInfo;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JTextField dateOfBirthText;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JLabel height;
    private javax.swing.JTextField heightText;
    private javax.swing.JLabel lastName;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JTextField phoneNumberText;
    private javax.swing.JButton saveDemo;
    private javax.swing.JLabel ssn;
    private javax.swing.JTextField ssnText;
    private javax.swing.JLabel weight;
    private javax.swing.JTextField weightText;
    // End of variables declaration//GEN-END:variables
}
