/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.DrivingLicense;
import Model.Person;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author shiva
 */
public class CreateDrivingLicensePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDrivingLicensePanel
     */
    public DrivingLicense drivingLicense;
    public Person person;
    public CreateDrivingLicensePanel(DrivingLicense driving, Person person) {
        initComponents();
        this.drivingLicense = driving;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateOfIssueText = new javax.swing.JTextField();
        dateOfExpiration = new javax.swing.JLabel();
        dateOfExpirationText = new javax.swing.JTextField();
        bloodType = new javax.swing.JLabel();
        bloodTypeText = new javax.swing.JTextField();
        licenseNumber = new javax.swing.JLabel();
        licenseNumberText = new javax.swing.JTextField();
        dateOfIssue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        BrowsePicture = new javax.swing.JButton();
        imgtextField = new javax.swing.JTextField();
        image = new javax.swing.JLabel();

        setBackground(new java.awt.Color(169, 228, 220));

        dateOfIssueText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        dateOfExpiration.setBackground(new java.awt.Color(0, 255, 0));
        dateOfExpiration.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateOfExpiration.setText("Date Of Expiration:");

        dateOfExpirationText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bloodType.setBackground(new java.awt.Color(0, 255, 0));
        bloodType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bloodType.setText("Blood Type:");

        bloodTypeText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        licenseNumber.setBackground(new java.awt.Color(0, 255, 0));
        licenseNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseNumber.setText("License Number:");

        licenseNumberText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumberTextActionPerformed(evt);
            }
        });

        dateOfIssue.setBackground(new java.awt.Color(0, 255, 0));
        dateOfIssue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateOfIssue.setText("Date Of Issue:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("PLEASE ENTER THE DRIVING LICENSE INFORMATION BELOW");

        Save.setBackground(new java.awt.Color(204, 0, 204));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        BrowsePicture.setText("Browse");
        BrowsePicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowsePictureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(dateOfIssueText))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(licenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(licenseNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dateOfExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dateOfExpirationText))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(bloodTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BrowsePicture)
                                .addGap(45, 45, 45)
                                .addComponent(imgtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(image)
                                .addGap(18, 18, 18)
                                .addComponent(Save)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfIssueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfExpirationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bloodTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BrowsePicture)
                    .addComponent(imgtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image)
                    .addComponent(Save))
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void licenseNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumberTextActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        this.drivingLicense.setLicenceNumber(licenseNumberText.getText());
        this.drivingLicense.setDateOfIssue(dateOfIssueText.getText());
        this.drivingLicense.setDateOfExpiration(dateOfExpirationText.getText());
        this.drivingLicense.setBloodGroup(bloodTypeText.getText());
        
        this.person.setDrivingLicense(this.drivingLicense);
        
        JOptionPane.showMessageDialog(this, "The License Info has been submitted Successfully.");
    }//GEN-LAST:event_SaveActionPerformed

    private void BrowsePictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowsePictureActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        imgtextField.setText(filename); 
        this.drivingLicense.setPicture(filename);
        ImageIcon i = new ImageIcon(filename);
        image.setIcon(i);
    }//GEN-LAST:event_BrowsePictureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowsePicture;
    private javax.swing.JButton Save;
    private javax.swing.JLabel bloodType;
    private javax.swing.JTextField bloodTypeText;
    private javax.swing.JLabel dateOfExpiration;
    private javax.swing.JTextField dateOfExpirationText;
    private javax.swing.JLabel dateOfIssue;
    private javax.swing.JTextField dateOfIssueText;
    private javax.swing.JLabel image;
    private javax.swing.JTextField imgtextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel licenseNumber;
    private javax.swing.JTextField licenseNumberText;
    // End of variables declaration//GEN-END:variables
}
