/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Address;

/**
 *
 * @author shiva
 */
public class ViewAddressPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAddressPanel
     */
    public Address address;
    public ViewAddressPanel(Address address) {
        initComponents();
        this.address = address;
        this.DisplayAddress();
    }
    
    public void DisplayAddress(){
        streetAddressTextArea.setText(this.address.getStreetAddress());
        cityText.setText(this.address.getCity());
        stateText.setText(this.address.getState());
        zipcodeText.setText(this.address.getZipCode());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAddressInfo = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        streetAddressTextArea = new javax.swing.JTextArea();
        zipcode = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        state = new javax.swing.JLabel();
        stateText = new javax.swing.JTextField();
        zipcodeText = new javax.swing.JTextField();
        streetAddress = new javax.swing.JLabel();

        setBackground(new java.awt.Color(169, 228, 220));

        createAddressInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createAddressInfo.setForeground(new java.awt.Color(255, 0, 0));
        createAddressInfo.setText("THE ADDRESS INFORMATION OF THE PERSON IS AS FOLLOWS");

        city.setBackground(new java.awt.Color(0, 255, 0));
        city.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        city.setText("City:");

        streetAddressTextArea.setEditable(false);
        streetAddressTextArea.setColumns(20);
        streetAddressTextArea.setRows(5);
        jScrollPane1.setViewportView(streetAddressTextArea);

        zipcode.setBackground(new java.awt.Color(0, 255, 0));
        zipcode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zipcode.setText("Zip Code:");

        cityText.setEditable(false);
        cityText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        state.setBackground(new java.awt.Color(0, 255, 0));
        state.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        state.setText("State:");

        stateText.setEditable(false);
        stateText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        zipcodeText.setEditable(false);
        zipcodeText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        streetAddress.setBackground(new java.awt.Color(0, 255, 0));
        streetAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        streetAddress.setText("Street Address:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(207, 207, 207)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(zipcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(streetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(createAddressInfo))
                    .addContainerGap(139, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(createAddressInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(streetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(zipcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(132, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel city;
    private javax.swing.JTextField cityText;
    private javax.swing.JLabel createAddressInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel state;
    private javax.swing.JTextField stateText;
    private javax.swing.JLabel streetAddress;
    private javax.swing.JTextArea streetAddressTextArea;
    private javax.swing.JLabel zipcode;
    private javax.swing.JTextField zipcodeText;
    // End of variables declaration//GEN-END:variables
}
