/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymodelui;
import product.Product;

/**
 *
 * @author Deepika Reddy
 */
public class adminPanel extends javax.swing.JPanel {

    /**
     * Creates new form adminPanel
     */
    Product main;
    public adminPanel(Product main) {
        initComponents();
        this.main=main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminSplit = new javax.swing.JSplitPane();
        adminPanel = new javax.swing.JPanel();
        addCoursebtn = new javax.swing.JButton();
        viewCoursebtn = new javax.swing.JButton();
        viewFacultybtn = new javax.swing.JButton();
        viewStudentbtn = new javax.swing.JButton();
        addFaculty = new javax.swing.JButton();
        addStudent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        adminSplit.setDividerLocation(160);

        addCoursebtn.setText("Add Course");
        addCoursebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCoursebtnActionPerformed(evt);
            }
        });

        viewCoursebtn.setText("View Course");
        viewCoursebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCoursebtnActionPerformed(evt);
            }
        });

        viewFacultybtn.setText("View Faculty");
        viewFacultybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFacultybtnActionPerformed(evt);
            }
        });

        viewStudentbtn.setText("View Student");
        viewStudentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentbtnActionPerformed(evt);
            }
        });

        addFaculty.setText("Add Faculty");
        addFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyActionPerformed(evt);
            }
        });

        addStudent.setText("Add Student");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Admin");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewStudentbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(addStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewCoursebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCoursebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewFacultybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(addCoursebtn)
                .addGap(18, 18, 18)
                .addComponent(viewCoursebtn)
                .addGap(13, 13, 13)
                .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(viewStudentbtn)
                .addGap(13, 13, 13)
                .addComponent(addFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewFacultybtn)
                .addGap(156, 156, 156))
        );

        adminSplit.setLeftComponent(adminPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        adminSplit.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminSplit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(adminSplit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCoursebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCoursebtnActionPerformed
        // TODO add your handling code here:
        addCoursePanel createPanel=new addCoursePanel(main);
        adminSplit.setRightComponent(createPanel);
        
    }//GEN-LAST:event_addCoursebtnActionPerformed

    private void viewCoursebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCoursebtnActionPerformed
        // TODO add your handling code here:
        viewCoursePanel viewPanel = new viewCoursePanel(main);
        adminSplit.setRightComponent(viewPanel);
        
    }//GEN-LAST:event_viewCoursebtnActionPerformed

    private void viewStudentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentbtnActionPerformed
        // TODO add your handling code here:
        viewStudentPanel1 viewPanel=new viewStudentPanel1(main);
        adminSplit.setRightComponent(viewPanel);
    }//GEN-LAST:event_viewStudentbtnActionPerformed

    private void viewFacultybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFacultybtnActionPerformed
        // TODO add your handling code here:
        viewFacultyPanel facultypanel= new viewFacultyPanel(main);
        adminSplit.setRightComponent(facultypanel);

        
    }//GEN-LAST:event_viewFacultybtnActionPerformed

    private void addFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyActionPerformed
        // TODO add your handling code here:
        addFacultyPanel createPanel=new addFacultyPanel(main);
        adminSplit.setRightComponent(createPanel);
    }//GEN-LAST:event_addFacultyActionPerformed

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        // TODO add your handling code here:
        addStudentPanel addStudent=new addStudentPanel(main);
        adminSplit.setRightComponent(addStudent);
    }//GEN-LAST:event_addStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCoursebtn;
    private javax.swing.JButton addFaculty;
    private javax.swing.JButton addStudent;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JSplitPane adminSplit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton viewCoursebtn;
    private javax.swing.JButton viewFacultybtn;
    private javax.swing.JButton viewStudentbtn;
    // End of variables declaration//GEN-END:variables
}
