/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymodelui;

import product.Product;

/**
 *
 * @author Deepika Reddy
 */
public class FacultyPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form FacultyPanel1
     */
    Product main;
    public FacultyPanel1(Product main) {
        initComponents();
        this.main=main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facultySplit = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        ViewFaculty = new javax.swing.JButton();
        ViewRatings = new javax.swing.JButton();
        ViewReviews = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        facultySplit.setDividerLocation(160);

        ViewFaculty.setText("View Faculty");
        ViewFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewFacultyActionPerformed(evt);
            }
        });

        ViewRatings.setText("View Ratings");
        ViewRatings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRatingsActionPerformed(evt);
            }
        });

        ViewReviews.setText("ViewReviews");
        ViewReviews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewReviewsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Faculty");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewReviews)
                            .addComponent(ViewRatings)
                            .addComponent(ViewFaculty)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(ViewFaculty)
                .addGap(28, 28, 28)
                .addComponent(ViewRatings)
                .addGap(30, 30, 30)
                .addComponent(ViewReviews)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        facultySplit.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2483, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        facultySplit.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(facultySplit, javax.swing.GroupLayout.PREFERRED_SIZE, 2649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facultySplit)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewFacultyActionPerformed
        // TODO add your handling code here:
         viewFacultyPanel courseFaculty = new viewFacultyPanel(main);
        facultySplit.setRightComponent(courseFaculty);
    }//GEN-LAST:event_ViewFacultyActionPerformed

    private void ViewRatingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRatingsActionPerformed
        // TODO add your handling code here:
        viewRatingPanel viewRating = new viewRatingPanel(main);
        facultySplit.setRightComponent(viewRating);
        
    }//GEN-LAST:event_ViewRatingsActionPerformed

    private void ViewReviewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewReviewsActionPerformed
        // TODO add your handling code here:
        viewReviewPanel viewRating = new viewReviewPanel(main);
        facultySplit.setRightComponent(viewRating);
    }//GEN-LAST:event_ViewReviewsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewFaculty;
    private javax.swing.JButton ViewRatings;
    private javax.swing.JButton ViewReviews;
    private javax.swing.JSplitPane facultySplit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
