/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.AccountInfo;
import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author shiva
 */
public class CreateBankAccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateBankAccountPanel
     */
    
    public AccountInfo savingsAccount;
    public AccountInfo checkingAccount;
    public Person person;
    public CreateBankAccountPanel(AccountInfo savings, AccountInfo checking, Person person) {
        initComponents();
        this.savingsAccount = savings;
        this.checkingAccount = checking;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createBankAccount = new javax.swing.JLabel();
        savingsRoutingText = new javax.swing.JTextField();
        savingsAccNumber = new javax.swing.JLabel();
        savingsAccountNumberText = new javax.swing.JTextField();
        savingsAccBalance = new javax.swing.JLabel();
        savingsAccountBalanceText = new javax.swing.JTextField();
        savingsBankName = new javax.swing.JLabel();
        savingsBankText = new javax.swing.JTextField();
        savingsRouting = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        savingsAccountInfo = new javax.swing.JLabel();
        checkingRoutingNumber = new javax.swing.JLabel();
        checkingRoutingNumberText = new javax.swing.JTextField();
        checkingAccNumber = new javax.swing.JLabel();
        checkingAccountNumberText = new javax.swing.JTextField();
        checkingAccBalance = new javax.swing.JLabel();
        checkingAccBalanceText = new javax.swing.JTextField();
        checkingBankName = new javax.swing.JLabel();
        checkingBankText = new javax.swing.JTextField();
        Save = new javax.swing.JButton();

        setBackground(new java.awt.Color(169, 228, 220));

        createBankAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createBankAccount.setForeground(new java.awt.Color(255, 0, 0));
        createBankAccount.setText("PLEASE ENTER THE BANKING ACCOUNT DETAILS BELOW");

        savingsRoutingText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        savingsAccNumber.setBackground(new java.awt.Color(0, 255, 0));
        savingsAccNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsAccNumber.setText("Account Number:");

        savingsAccountNumberText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        savingsAccBalance.setBackground(new java.awt.Color(0, 255, 0));
        savingsAccBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsAccBalance.setText("Account Balance:");

        savingsAccountBalanceText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        savingsBankName.setBackground(new java.awt.Color(0, 255, 0));
        savingsBankName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsBankName.setText("Bank Name:");

        savingsBankText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsBankText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsBankTextActionPerformed(evt);
            }
        });

        savingsRouting.setBackground(new java.awt.Color(0, 255, 0));
        savingsRouting.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsRouting.setText("Routing Number:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("SAVINGS ACCOUNT INFO");

        savingsAccountInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savingsAccountInfo.setForeground(new java.awt.Color(0, 0, 255));
        savingsAccountInfo.setText("CHECKING ACCOUNT INFO");

        checkingRoutingNumber.setBackground(new java.awt.Color(0, 255, 0));
        checkingRoutingNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingRoutingNumber.setText("Routing Number:");

        checkingRoutingNumberText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        checkingAccNumber.setBackground(new java.awt.Color(0, 255, 0));
        checkingAccNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingAccNumber.setText("Account Number:");

        checkingAccountNumberText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        checkingAccBalance.setBackground(new java.awt.Color(0, 255, 0));
        checkingAccBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingAccBalance.setText("Account Balance:");

        checkingAccBalanceText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        checkingBankName.setBackground(new java.awt.Color(0, 255, 0));
        checkingBankName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingBankName.setText("Bank Name:");

        checkingBankText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingBankText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingBankTextActionPerformed(evt);
            }
        });

        Save.setBackground(new java.awt.Color(204, 0, 204));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(createBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savingsAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(savingsBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(savingsBankText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(savingsRouting, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(savingsRoutingText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(savingsAccBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(savingsAccNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(savingsAccountNumberText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savingsAccountBalanceText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkingBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(checkingBankText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkingRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(checkingRoutingNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(checkingAccBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkingAccNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkingAccountNumberText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkingAccBalanceText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(Save)))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(createBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savingsBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingsBankText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savingsRouting, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingsRoutingText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savingsAccNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingsAccountNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savingsAccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingsAccountBalanceText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savingsAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkingBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkingBankText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkingRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkingRoutingNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkingAccNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkingAccountNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkingAccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkingAccBalanceText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Save)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void savingsBankTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsBankTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsBankTextActionPerformed

    private void checkingBankTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingBankTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkingBankTextActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        this.savingsAccount.setBankName(savingsBankText.getText());
        this.savingsAccount.setBankRoutingNumber(savingsRoutingText.getText());
        this.savingsAccount.setBankAccountNumber(savingsAccountNumberText.getText());
        this.savingsAccount.setAccountBalance(Long.parseLong(savingsAccountBalanceText.getText()));
        
        person.setSavingsAccount(this.savingsAccount);
        
        this.checkingAccount.setBankName(checkingBankText.getText());
        this.checkingAccount.setBankRoutingNumber(checkingRoutingNumberText.getText());
        this.checkingAccount.setBankAccountNumber(checkingAccountNumberText.getText());
        this.checkingAccount.setAccountBalance(Long.parseLong(checkingAccBalanceText.getText()));
        
        person.setCheckingAccount(this.checkingAccount);
        
        JOptionPane.showMessageDialog(this, "The Bank Account Information has been submitted successfully.");
        
    }//GEN-LAST:event_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JLabel checkingAccBalance;
    private javax.swing.JTextField checkingAccBalanceText;
    private javax.swing.JLabel checkingAccNumber;
    private javax.swing.JTextField checkingAccountNumberText;
    private javax.swing.JLabel checkingBankName;
    private javax.swing.JTextField checkingBankText;
    private javax.swing.JLabel checkingRoutingNumber;
    private javax.swing.JTextField checkingRoutingNumberText;
    private javax.swing.JLabel createBankAccount;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel savingsAccBalance;
    private javax.swing.JLabel savingsAccNumber;
    private javax.swing.JTextField savingsAccountBalanceText;
    private javax.swing.JLabel savingsAccountInfo;
    private javax.swing.JTextField savingsAccountNumberText;
    private javax.swing.JLabel savingsBankName;
    private javax.swing.JTextField savingsBankText;
    private javax.swing.JLabel savingsRouting;
    private javax.swing.JTextField savingsRoutingText;
    // End of variables declaration//GEN-END:variables
}
