/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Model.MedicalRecord;
import Model.Person;
import javax.swing.JOptionPane;
/**
 *
 * @author shiva
 */
public class CreateMedicalRecordPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateMedicalRecordPanel
     */
    public MedicalRecord medicalRecord;
    public Person person;
    public CreateMedicalRecordPanel(MedicalRecord medical, Person person) {
        initComponents();
        this.medicalRecord = medical;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allergy1Text = new javax.swing.JTextField();
        allergy2 = new javax.swing.JLabel();
        allergy2Text = new javax.swing.JTextField();
        allergy3 = new javax.swing.JLabel();
        allergy3Text = new javax.swing.JTextField();
        recordNumber = new javax.swing.JLabel();
        recordNumberText = new javax.swing.JTextField();
        allergy1 = new javax.swing.JLabel();
        medicalRecordInfo = new javax.swing.JLabel();
        Save = new javax.swing.JButton();

        setBackground(new java.awt.Color(169, 228, 220));

        allergy1Text.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        allergy2.setBackground(new java.awt.Color(0, 255, 0));
        allergy2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        allergy2.setText("Allergy2:");

        allergy2Text.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        allergy3.setBackground(new java.awt.Color(0, 255, 0));
        allergy3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        allergy3.setText("Allergy3:");

        allergy3Text.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        recordNumber.setBackground(new java.awt.Color(0, 255, 0));
        recordNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        recordNumber.setText("Record Number:");

        recordNumberText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        recordNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordNumberTextActionPerformed(evt);
            }
        });

        allergy1.setBackground(new java.awt.Color(0, 255, 0));
        allergy1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        allergy1.setText("Allergy1:");

        medicalRecordInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        medicalRecordInfo.setForeground(new java.awt.Color(255, 0, 0));
        medicalRecordInfo.setText("PLEASE ENTER THE MEDICAL RECORD INFORMATION");

        Save.setBackground(new java.awt.Color(255, 0, 204));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medicalRecordInfo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(allergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(allergy1Text))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(recordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(recordNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(allergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(allergy2Text))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(allergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(allergy3Text, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(Save)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(medicalRecordInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recordNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergy1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergy2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allergy3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(Save)
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void recordNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recordNumberTextActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        
        this.medicalRecord.setMedicalRecordNumber(recordNumberText.getText());
        this.medicalRecord.setAllergy1((allergy1Text.getText()));
        this.medicalRecord.setAllergy2((allergy2Text.getText()));
        this.medicalRecord.setAllergy3((allergy3Text.getText()));
        
        this.person.setMedicalRecord(this.medicalRecord);
        
        JOptionPane.showMessageDialog(this, "The Medical Record Info has  been successfully submitted.");
    }//GEN-LAST:event_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JLabel allergy1;
    private javax.swing.JTextField allergy1Text;
    private javax.swing.JLabel allergy2;
    private javax.swing.JTextField allergy2Text;
    private javax.swing.JLabel allergy3;
    private javax.swing.JTextField allergy3Text;
    private javax.swing.JLabel medicalRecordInfo;
    private javax.swing.JLabel recordNumber;
    private javax.swing.JTextField recordNumberText;
    // End of variables declaration//GEN-END:variables
}
