/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Demographic;
import Model.Person;
import Model.AccountInfo;
import Model.DrivingLicense;
import Model.MedicalRecord;
import Model.Address;
import javax.swing.ImageIcon;

/**
 *
 * @author shiva
 */
public class ViewFullReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFullReportPanel
     */
    public Person person;
    public ViewFullReportPanel(Person person) {
        initComponents();
        this.person = person;
        this.DisplayFullReport();
    }
    
    public void DisplayFullReport(){
        Demographic demo = this.person.getDemographicInfo();
        
        this.firstNameText.setText(demo.FirstName);
        this.lastNameText.setText(demo.LastName);
        this.phoneNumberText.setText(demo.PhoneNumber);
        this.dateOfBirthText.setText(demo.getDateOfBirth());
       this.ageText.setText(Integer.toString(demo.getAge()));
       this.heightText.setText(Integer.toString(demo.getHeight()));
       this.weightText.setText(Integer.toString(demo.getWeight()));
       this.ssnText.setText(demo.getSocialSecurityNumber());
       
       Address address = this.person.getAddressInfo();
       
       this.streetAddressTextArea.setText(address.getStreetAddress());
       this.cityText.setText(address.getCity());
       this.stateText.setText(address.getState());
       this.zipcodeText.setText(address.getZipCode());
        
        AccountInfo savingsAccount = this.person.getSavingsAccount();
        
        savingsBankText1.setText(savingsAccount.BankName);
        savingsRoutingText1.setText(savingsAccount.BankRoutingNumber);
        savingsAccountNumberText1.setText(savingsAccount.BankAccountNumber);
        savingsAccountBalanceText1.setText(Long.toString(savingsAccount.AccountBalance));
        
        AccountInfo checkingAccount = this.person.getCheckingAccount();
        
        checkingBankText1.setText(checkingAccount.BankName);
        checkingRoutingNumberText1.setText(checkingAccount.BankRoutingNumber);
        checkingAccountNumberText1.setText(checkingAccount.BankAccountNumber);
        checkingAccBalanceText1.setText(Long.toString(checkingAccount.AccountBalance));
        
        DrivingLicense drivingLicense = this.person.getDrivingLicense();
        
        this.licenseNumberText.setText(drivingLicense.LicenceNumber);
        this.dateOfIssueText.setText(drivingLicense.DateOfIssue);
        this.dateOfExpirationText.setText(drivingLicense.DateOfExpiration);
        this.bloodTypeText.setText(drivingLicense.BloodGroup);
        ImageIcon i = new ImageIcon(drivingLicense.getPicture());
        image2.setIcon(i);
        
        MedicalRecord medicalRecord = this.person.getMedicalRecord();
        
        this.recordNumberText.setText(medicalRecord.MedicalRecordNumber);
        this.allergy1Text.setText(medicalRecord.Allergy1);
        this.allergy2Text.setText(medicalRecord.Allergy2);
        this.allergy3Text.setText(medicalRecord.Allergy3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        savingsAccountInfo = new javax.swing.JLabel();
        checkingAccNumber = new javax.swing.JLabel();
        savingsRouting = new javax.swing.JLabel();
        checkingAccountNumberText = new javax.swing.JTextField();
        checkingAccBalance = new javax.swing.JLabel();
        checkingAccBalanceText = new javax.swing.JTextField();
        checkingBankName = new javax.swing.JLabel();
        savingsRoutingText = new javax.swing.JTextField();
        checkingBankText = new javax.swing.JTextField();
        savingsAccNumber = new javax.swing.JLabel();
        checkingRoutingNumberText = new javax.swing.JTextField();
        savingsAccountNumberText = new javax.swing.JTextField();
        savingsAccBalance = new javax.swing.JLabel();
        savingsAccountBalanceText = new javax.swing.JTextField();
        checkingRoutingNumber = new javax.swing.JLabel();
        savingsBankName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        savingsBankText = new javax.swing.JTextField();
        createBankAccount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dateOfBirthText = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        height = new javax.swing.JLabel();
        ssn = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JLabel();
        heightText = new javax.swing.JTextField();
        ssnText = new javax.swing.JTextField();
        firstNameText = new javax.swing.JTextField();
        phoneNumberText = new javax.swing.JTextField();
        weight = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        dateOfBirth = new javax.swing.JLabel();
        weightText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        zipcode = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        state = new javax.swing.JLabel();
        stateText = new javax.swing.JTextField();
        zipcodeText = new javax.swing.JTextField();
        streetAddress = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        streetAddressTextArea = new javax.swing.JTextArea();
        savingsAccountInfo1 = new javax.swing.JLabel();
        checkingAccNumber1 = new javax.swing.JLabel();
        savingsRouting1 = new javax.swing.JLabel();
        checkingAccountNumberText1 = new javax.swing.JTextField();
        checkingAccBalance1 = new javax.swing.JLabel();
        checkingAccBalanceText1 = new javax.swing.JTextField();
        checkingBankName1 = new javax.swing.JLabel();
        savingsRoutingText1 = new javax.swing.JTextField();
        checkingBankText1 = new javax.swing.JTextField();
        savingsAccNumber1 = new javax.swing.JLabel();
        checkingRoutingNumberText1 = new javax.swing.JTextField();
        savingsAccountNumberText1 = new javax.swing.JTextField();
        savingsAccBalance1 = new javax.swing.JLabel();
        savingsAccountBalanceText1 = new javax.swing.JTextField();
        checkingRoutingNumber1 = new javax.swing.JLabel();
        savingsBankName1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        savingsBankText1 = new javax.swing.JTextField();
        allergy1Text = new javax.swing.JTextField();
        allergy2 = new javax.swing.JLabel();
        allergy2Text = new javax.swing.JTextField();
        allergy3 = new javax.swing.JLabel();
        allergy3Text = new javax.swing.JTextField();
        recordNumber = new javax.swing.JLabel();
        recordNumberText = new javax.swing.JTextField();
        allergy1 = new javax.swing.JLabel();
        medicalRecordInfo = new javax.swing.JLabel();
        dateOfIssue = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dateOfIssueText = new javax.swing.JTextField();
        dateOfExpiration = new javax.swing.JLabel();
        dateOfExpirationText = new javax.swing.JTextField();
        bloodType = new javax.swing.JLabel();
        bloodTypeText = new javax.swing.JTextField();
        licenseNumber = new javax.swing.JLabel();
        licenseNumberText = new javax.swing.JTextField();
        image2 = new javax.swing.JLabel();

        savingsAccountInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savingsAccountInfo.setForeground(new java.awt.Color(0, 0, 255));
        savingsAccountInfo.setText("CHECKING ACCOUNT INFO");

        checkingAccNumber.setBackground(new java.awt.Color(0, 255, 0));
        checkingAccNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingAccNumber.setText("Account Number:");

        savingsRouting.setBackground(new java.awt.Color(0, 255, 0));
        savingsRouting.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsRouting.setText("Routing Number:");

        checkingAccountNumberText.setEditable(false);
        checkingAccountNumberText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        checkingAccBalance.setBackground(new java.awt.Color(0, 255, 0));
        checkingAccBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingAccBalance.setText("Account Balance:");

        checkingAccBalanceText.setEditable(false);
        checkingAccBalanceText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        checkingBankName.setBackground(new java.awt.Color(0, 255, 0));
        checkingBankName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingBankName.setText("Bank Name:");

        savingsRoutingText.setEditable(false);
        savingsRoutingText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        checkingBankText.setEditable(false);
        checkingBankText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingBankText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingBankTextActionPerformed(evt);
            }
        });

        savingsAccNumber.setBackground(new java.awt.Color(0, 255, 0));
        savingsAccNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsAccNumber.setText("Account Number:");

        checkingRoutingNumberText.setEditable(false);
        checkingRoutingNumberText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        savingsAccountNumberText.setEditable(false);
        savingsAccountNumberText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        savingsAccBalance.setBackground(new java.awt.Color(0, 255, 0));
        savingsAccBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsAccBalance.setText("Account Balance:");

        savingsAccountBalanceText.setEditable(false);
        savingsAccountBalanceText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        checkingRoutingNumber.setBackground(new java.awt.Color(0, 255, 0));
        checkingRoutingNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingRoutingNumber.setText("Routing Number:");

        savingsBankName.setBackground(new java.awt.Color(0, 255, 0));
        savingsBankName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsBankName.setText("Bank Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("SAVINGS ACCOUNT INFO");

        savingsBankText.setEditable(false);
        savingsBankText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsBankText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsBankTextActionPerformed(evt);
            }
        });

        createBankAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createBankAccount.setForeground(new java.awt.Color(255, 0, 0));
        createBankAccount.setText("THE BANKING ACCOUNT DETAILS ARE AS FOLLOWS");

        setBackground(new java.awt.Color(169, 228, 220));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("DEMOGRAPHIC INFORMATION");

        dateOfBirthText.setEditable(false);
        dateOfBirthText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        age.setBackground(new java.awt.Color(0, 255, 0));
        age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        age.setText("Age:");

        ageText.setEditable(false);
        ageText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lastNameText.setEditable(false);
        lastNameText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        height.setBackground(new java.awt.Color(0, 255, 0));
        height.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        height.setText("Height:");

        ssn.setBackground(new java.awt.Color(0, 255, 0));
        ssn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ssn.setText("SSN:");

        firstName.setBackground(new java.awt.Color(0, 255, 0));
        firstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        firstName.setText("First Name:");

        phoneNumber.setBackground(new java.awt.Color(0, 255, 0));
        phoneNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phoneNumber.setText("Phone Number:");

        heightText.setEditable(false);
        heightText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ssnText.setEditable(false);
        ssnText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        firstNameText.setEditable(false);
        firstNameText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        phoneNumberText.setEditable(false);
        phoneNumberText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        weight.setBackground(new java.awt.Color(0, 255, 0));
        weight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        weight.setText("Weight:");

        lastName.setBackground(new java.awt.Color(0, 255, 0));
        lastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lastName.setText("Last Name:");

        dateOfBirth.setBackground(new java.awt.Color(0, 255, 0));
        dateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateOfBirth.setText("Date Of Birth:");

        weightText.setEditable(false);
        weightText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("ADDRESS INFORMATION");

        zipcode.setBackground(new java.awt.Color(0, 255, 0));
        zipcode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zipcode.setText("Zip Code:");

        cityText.setEditable(false);
        cityText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        state.setBackground(new java.awt.Color(0, 255, 0));
        state.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        state.setText("State:");

        stateText.setEditable(false);
        stateText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        zipcodeText.setEditable(false);
        zipcodeText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        streetAddress.setBackground(new java.awt.Color(0, 255, 0));
        streetAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        streetAddress.setText("Street Address:");

        city.setBackground(new java.awt.Color(0, 255, 0));
        city.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        city.setText("City:");

        streetAddressTextArea.setEditable(false);
        streetAddressTextArea.setColumns(20);
        streetAddressTextArea.setRows(5);
        jScrollPane1.setViewportView(streetAddressTextArea);

        savingsAccountInfo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savingsAccountInfo1.setForeground(new java.awt.Color(0, 0, 255));
        savingsAccountInfo1.setText("CHECKING ACCOUNT INFO");

        checkingAccNumber1.setBackground(new java.awt.Color(0, 255, 0));
        checkingAccNumber1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingAccNumber1.setText("Account Number:");

        savingsRouting1.setBackground(new java.awt.Color(0, 255, 0));
        savingsRouting1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsRouting1.setText("Routing Number:");

        checkingAccountNumberText1.setEditable(false);
        checkingAccountNumberText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        checkingAccBalance1.setBackground(new java.awt.Color(0, 255, 0));
        checkingAccBalance1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingAccBalance1.setText("Account Balance:");

        checkingAccBalanceText1.setEditable(false);
        checkingAccBalanceText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        checkingBankName1.setBackground(new java.awt.Color(0, 255, 0));
        checkingBankName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingBankName1.setText("Bank Name:");

        savingsRoutingText1.setEditable(false);
        savingsRoutingText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        checkingBankText1.setEditable(false);
        checkingBankText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingBankText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingBankText1ActionPerformed(evt);
            }
        });

        savingsAccNumber1.setBackground(new java.awt.Color(0, 255, 0));
        savingsAccNumber1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsAccNumber1.setText("Account Number:");

        checkingRoutingNumberText1.setEditable(false);
        checkingRoutingNumberText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        savingsAccountNumberText1.setEditable(false);
        savingsAccountNumberText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        savingsAccBalance1.setBackground(new java.awt.Color(0, 255, 0));
        savingsAccBalance1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsAccBalance1.setText("Account Balance:");

        savingsAccountBalanceText1.setEditable(false);
        savingsAccountBalanceText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        checkingRoutingNumber1.setBackground(new java.awt.Color(0, 255, 0));
        checkingRoutingNumber1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkingRoutingNumber1.setText("Routing Number:");

        savingsBankName1.setBackground(new java.awt.Color(0, 255, 0));
        savingsBankName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsBankName1.setText("Bank Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("SAVINGS ACCOUNT INFO");

        savingsBankText1.setEditable(false);
        savingsBankText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        savingsBankText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsBankText1ActionPerformed(evt);
            }
        });

        allergy1Text.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        allergy2.setBackground(new java.awt.Color(0, 255, 0));
        allergy2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        allergy2.setText("Allergy2:");

        allergy2Text.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        allergy3.setBackground(new java.awt.Color(0, 255, 0));
        allergy3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        allergy3.setText("Allergy3:");

        allergy3Text.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        recordNumber.setBackground(new java.awt.Color(0, 255, 0));
        recordNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        recordNumber.setText("Record Number:");

        recordNumberText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        recordNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordNumberTextActionPerformed(evt);
            }
        });

        allergy1.setBackground(new java.awt.Color(0, 255, 0));
        allergy1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        allergy1.setText("Allergy1:");

        medicalRecordInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        medicalRecordInfo.setForeground(new java.awt.Color(255, 0, 0));
        medicalRecordInfo.setText("THE MEDICAL RECORD INFORMATION IS AS FOLLOWS");

        dateOfIssue.setBackground(new java.awt.Color(0, 255, 0));
        dateOfIssue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateOfIssue.setText("Date Of Issue:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("THE DRIVING LICENSE INFORMATION SUBMITTED IS AS FOLLOWS");

        dateOfIssueText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateOfIssueText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfIssueTextActionPerformed(evt);
            }
        });

        dateOfExpiration.setBackground(new java.awt.Color(0, 255, 0));
        dateOfExpiration.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateOfExpiration.setText("Date Of Expiration:");

        dateOfExpirationText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bloodType.setBackground(new java.awt.Color(0, 255, 0));
        bloodType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bloodType.setText("Blood Type:");

        bloodTypeText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        licenseNumber.setBackground(new java.awt.Color(0, 255, 0));
        licenseNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseNumber.setText("License Number:");

        licenseNumberText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumberTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(streetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(ssnText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(weightText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(heightText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(ageText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(dateOfBirthText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(phoneNumberText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(lastNameText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(dateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(licenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(dateOfIssueText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(licenseNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(dateOfExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(15, 15, 15))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(bloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bloodTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(dateOfExpirationText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(image2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(zipcodeText, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stateText))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cityText)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medicalRecordInfo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(allergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(allergy1Text))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(recordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(recordNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(allergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(allergy2Text))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(allergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(allergy3Text, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(67, 67, 67)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingsAccountInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savingsBankName1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(savingsBankText1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savingsRouting1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savingsRoutingText1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(savingsAccBalance1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(savingsAccNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savingsAccountNumberText1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savingsAccountBalanceText1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkingBankName1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkingBankText1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkingRoutingNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkingRoutingNumberText1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(checkingAccBalance1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkingAccNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkingAccountNumberText1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkingAccBalanceText1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licenseNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOfIssueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOfExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOfExpirationText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dateOfBirthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bloodTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(weightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(streetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(savingsBankName1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savingsBankText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(savingsRouting1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savingsRoutingText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(savingsAccNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savingsAccountNumberText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(savingsAccBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savingsAccountBalanceText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(savingsAccountInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(image2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkingBankName1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkingBankText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkingRoutingNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkingRoutingNumberText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkingAccNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkingAccountNumberText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkingAccBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkingAccBalanceText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zipcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(medicalRecordInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recordNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergy1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergy2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allergy3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkingBankTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingBankTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingBankTextActionPerformed

    private void savingsBankTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsBankTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsBankTextActionPerformed

    private void checkingBankText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingBankText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingBankText1ActionPerformed

    private void savingsBankText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsBankText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsBankText1ActionPerformed

    private void recordNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recordNumberTextActionPerformed

    private void licenseNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumberTextActionPerformed

    private void dateOfIssueTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfIssueTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfIssueTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JTextField ageText;
    private javax.swing.JLabel allergy1;
    private javax.swing.JTextField allergy1Text;
    private javax.swing.JLabel allergy2;
    private javax.swing.JTextField allergy2Text;
    private javax.swing.JLabel allergy3;
    private javax.swing.JTextField allergy3Text;
    private javax.swing.JLabel bloodType;
    private javax.swing.JTextField bloodTypeText;
    private javax.swing.JLabel checkingAccBalance;
    private javax.swing.JLabel checkingAccBalance1;
    private javax.swing.JTextField checkingAccBalanceText;
    private javax.swing.JTextField checkingAccBalanceText1;
    private javax.swing.JLabel checkingAccNumber;
    private javax.swing.JLabel checkingAccNumber1;
    private javax.swing.JTextField checkingAccountNumberText;
    private javax.swing.JTextField checkingAccountNumberText1;
    private javax.swing.JLabel checkingBankName;
    private javax.swing.JLabel checkingBankName1;
    private javax.swing.JTextField checkingBankText;
    private javax.swing.JTextField checkingBankText1;
    private javax.swing.JLabel checkingRoutingNumber;
    private javax.swing.JLabel checkingRoutingNumber1;
    private javax.swing.JTextField checkingRoutingNumberText;
    private javax.swing.JTextField checkingRoutingNumberText1;
    private javax.swing.JLabel city;
    private javax.swing.JTextField cityText;
    private javax.swing.JLabel createBankAccount;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JTextField dateOfBirthText;
    private javax.swing.JLabel dateOfExpiration;
    private javax.swing.JTextField dateOfExpirationText;
    private javax.swing.JLabel dateOfIssue;
    private javax.swing.JTextField dateOfIssueText;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JLabel height;
    private javax.swing.JTextField heightText;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastName;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JLabel licenseNumber;
    private javax.swing.JTextField licenseNumberText;
    private javax.swing.JLabel medicalRecordInfo;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JTextField phoneNumberText;
    private javax.swing.JLabel recordNumber;
    private javax.swing.JTextField recordNumberText;
    private javax.swing.JLabel savingsAccBalance;
    private javax.swing.JLabel savingsAccBalance1;
    private javax.swing.JLabel savingsAccNumber;
    private javax.swing.JLabel savingsAccNumber1;
    private javax.swing.JTextField savingsAccountBalanceText;
    private javax.swing.JTextField savingsAccountBalanceText1;
    private javax.swing.JLabel savingsAccountInfo;
    private javax.swing.JLabel savingsAccountInfo1;
    private javax.swing.JTextField savingsAccountNumberText;
    private javax.swing.JTextField savingsAccountNumberText1;
    private javax.swing.JLabel savingsBankName;
    private javax.swing.JLabel savingsBankName1;
    private javax.swing.JTextField savingsBankText;
    private javax.swing.JTextField savingsBankText1;
    private javax.swing.JLabel savingsRouting;
    private javax.swing.JLabel savingsRouting1;
    private javax.swing.JTextField savingsRoutingText;
    private javax.swing.JTextField savingsRoutingText1;
    private javax.swing.JLabel ssn;
    private javax.swing.JTextField ssnText;
    private javax.swing.JLabel state;
    private javax.swing.JTextField stateText;
    private javax.swing.JLabel streetAddress;
    private javax.swing.JTextArea streetAddressTextArea;
    private javax.swing.JLabel weight;
    private javax.swing.JTextField weightText;
    private javax.swing.JLabel zipcode;
    private javax.swing.JTextField zipcodeText;
    // End of variables declaration//GEN-END:variables
}
