/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Model.DrivingLicense;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author shiva
 */
public class ViewLicenseInformationPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewLicenseInformationPanel
     */
    public DrivingLicense drivingLicense;
    public ViewLicenseInformationPanel(DrivingLicense license) {
        initComponents();
        this.drivingLicense = license;
        this.DisplayLicense();
    }

    public void DisplayLicense(){
        this.licenseNumberText2.setText(this.drivingLicense.LicenceNumber);
        this.dateOfIssueText.setText(this.drivingLicense.DateOfIssue);
        this.dateOfExpirationText.setText(this.drivingLicense.DateOfExpiration);
        this.bloodTypeText.setText(this.drivingLicense.BloodGroup);
        ImageIcon i = new ImageIcon(this.drivingLicense.getPicture());
        image2.setIcon(i);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateOfIssueText = new javax.swing.JTextField();
        dateOfExpiration = new javax.swing.JLabel();
        dateOfExpirationText = new javax.swing.JTextField();
        bloodType = new javax.swing.JLabel();
        bloodTypeText = new javax.swing.JTextField();
        licenseNumber = new javax.swing.JLabel();
        licenseNumberText2 = new javax.swing.JTextField();
        dateOfIssue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        image2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(169, 228, 220));

        dateOfIssueText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        dateOfExpiration.setBackground(new java.awt.Color(0, 255, 0));
        dateOfExpiration.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateOfExpiration.setText("Date Of Expiration:");

        dateOfExpirationText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bloodType.setBackground(new java.awt.Color(0, 255, 0));
        bloodType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bloodType.setText("Blood Type:");

        bloodTypeText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        licenseNumber.setBackground(new java.awt.Color(0, 255, 0));
        licenseNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseNumber.setText("License Number:");

        licenseNumberText2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        licenseNumberText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumberText2ActionPerformed(evt);
            }
        });

        dateOfIssue.setBackground(new java.awt.Color(0, 255, 0));
        dateOfIssue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateOfIssue.setText("Date Of Issue:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("THE DRIVING LICENSE INFORMATION SUBMITTED IS AS FOLLOWS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dateOfExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dateOfExpirationText, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                        .addComponent(bloodTypeText)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(licenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(licenseNumberText2, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                        .addComponent(dateOfIssueText)))))
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(image2)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseNumberText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfIssueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfExpirationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void licenseNumberText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumberText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumberText2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodType;
    private javax.swing.JTextField bloodTypeText;
    private javax.swing.JLabel dateOfExpiration;
    private javax.swing.JTextField dateOfExpirationText;
    private javax.swing.JLabel dateOfIssue;
    private javax.swing.JTextField dateOfIssueText;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel licenseNumber;
    private javax.swing.JTextField licenseNumberText;
    private javax.swing.JTextField licenseNumberText1;
    private javax.swing.JTextField licenseNumberText2;
    // End of variables declaration//GEN-END:variables
}
